[[redirect]]
from = "/*"
to = "/public/index.html"
status = 200

[build]
command = "npm run build "
publish = "/opt/build/repo/build"
base = "/opt/build/repo"

base: 
commandOrigin: config
publishOrigin: config
