[[redirect]]
from = "/*"
to = "/public/index.html"
status = 200

[build]
command = "npm run build "
publish = "/build"
base = "/"

base: /opt/build/repo
command: 'npm run build '
commandOrigin: config
publish: /opt/build/repo/build
publishOrigin: config
