[build-dependencies]
  command = "npm run build"
  oublish = "/build"
  base= "/"

[[redirects]]
  from = "/search"
  to = "https://api.mysearch.com"
  status = 200
  force = true
  signed = "API_SIGNATURE_TOKEN_PLACEHOLDER"